name: master

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo
        uses: s4u/setup-maven-action@v1.2.1
        with:
          checkout-fetch-depth: 0
          java-version: 17
          maven-version: 3.8.6

      - name: build the job
        id: btj
        run: |
          mvn clean install

      - name: running the jar file
        id: rtjf
        run: |
          cp ${{ github.workspace }}/target/demo-0.0.1-SNAPSHOT.jar ${{ github.workspace }}/test.jar
          ls -ltr
          java -jar test.jar &  
          echo git status

#                ("&" is used)   to run the jar file in the  background so that the process can be terminated
#                 because if we run jar file in the foreground then it cant be terminated
      - name: aborting the jar file run
        id: atjfr
        run: |
          pkill -f "test.jar"      || echo "process not found"
